version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql8-container
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
